In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\Users\k18at\Downloads\weather_forecast_data.csv')

In [41]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  2500 non-null   float64
 1   Humidity     2500 non-null   float64
 2   Wind_Speed   2500 non-null   float64
 3   Cloud_Cover  2500 non-null   float64
 4   Pressure     2500 non-null   float64
 5   Rain         2500 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 117.3 KB


In [7]:
x = dataset.iloc[:,:2].values
y = dataset.iloc[:,-1].values

In [9]:
x

array([[23.7203376 , 89.59264065],
       [27.87973416, 46.48970404],
       [25.0690844 , 83.07284289],
       ...,
       [28.10827448, 43.81717836],
       [14.78927534, 57.90810538],
       [26.55435586, 97.10151721]])

In [11]:
y

array(['rain', 'no rain', 'no rain', ..., 'no rain', 'no rain', 'no rain'],
      dtype=object)

In [13]:
dataset.isnull().sum()

Temperature    0
Humidity       0
Wind_Speed     0
Cloud_Cover    0
Pressure       0
Rain           0
dtype: int64

In [43]:
x = dataset[["Temperature","Humidity"]]
y = dataset['Rain']

In [49]:
x

Temperature   Humidity
0       23.720338  89.592641
1       27.879734  46.489704
2       25.069084  83.072843
3       23.622080  74.367758
4       20.591370  96.858822
...           ...        ...
2495    21.791602  45.270902
2496    27.558479  46.481744
2497    28.108274  43.817178
2498    14.789275  57.908105
2499    26.554356  97.101517

[2500 rows x 2 columns]

In [51]:
y.replace(['rain','no rain'],
                        [0,1],inplace=True)

In [53]:
y

0       0
1       1
2       1
3       0
4       1
       ..
2495    1
2496    1
2497    1
2498    1
2499    1
Name: Rain, Length: 2500, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state = 0)

In [57]:

np.shape(x_train),np.shape(x_test)

((2000, 2), (500, 2))

In [59]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

In [61]:
y_train

286     1
1495    1
40      1
1106    1
1379    1
       ..
1033    1
1731    1
763     1
835     1
1653    1
Name: Rain, Length: 2000, dtype: int64

In [63]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression( )
lr.fit(x_train,y_train)

LogisticRegression()

In [77]:
lr.predict( [[23.720338 ,	89.592641]])

array([0], dtype=int64)

In [69]:
y_pred = lr.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [71]:
# concating predict result and given result
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

AttributeError: 'Series' object has no attribute 'reshape'

In [73]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[ 16  50]
 [ 16 418]]


In [75]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.868